import { HelperProfile, PointsEvent } from "@/lib/types";

export const MOCK_HELPER_PROFILES: HelperProfile[] = [
  {
    id: "h1",
    userId: "u3",
    skills: ["מתמטיקה", "פיזיקה", "תכנות", "מחשבים"],
    availability: "ימי ב' ו-ד' אחה\"צ, סופי שבוע לפי תיאום",
    bio: "תלמיד י\"א שאוהב מדעים וטכנולוגיה. עזרתי עד כה ל-12 תלמידים ומרגיש שזה הדבר הכי שווה שעשיתי בחיי הבית ספריים.",
    categories: ["לימודי", "טכני"],
    isApproved: true,
    helpCount: 12,
    approvalStatus: "approved",
    submittedAt: "2024-09-05T10:00:00",
  },
  {
    id: "h2",
    userId: "u1",
    skills: ["כתיבה יוצרת", "עריכה", "עברית", "ספרות"],
    availability: "ימי א' ו-ג' בצהריים",
    bio: "אוהבת לכתוב ולעזור לאחרים לבטא את עצמם. אם יש לך קושי בחיבורים או בעבודות כתיבה – בואי נשב ביחד.",
    categories: ["לימודי", "יצירתי"],
    isApproved: true,
    helpCount: 7,
    approvalStatus: "approved",
    submittedAt: "2024-09-06T11:00:00",
  },
  {
    id: "h3",
    userId: "u5",
    skills: ["עיצוב גרפי", "Canva", "PowerPoint", "מולטימדיה"],
    availability: "גמיש – לפי תיאום מראש",
    bio: "מתעסק בעיצוב גרפי כתחביב וגם כמקצוע עתידי. אשמח לעזור בכל מה שקשור לעיצוב, מצגות, פליירים ולוגואים.",
    categories: ["יצירתי", "ארגוני"],
    isApproved: true,
    helpCount: 5,
    approvalStatus: "approved",
    submittedAt: "2024-09-07T09:00:00",
  },
  {
    id: "h4",
    userId: "u12",
    skills: ["אנגלית", "תרגום", "הכנה לבגרות"],
    availability: "ימי ג' וה' 14:00–16:00",
    bio: "גדלתי בחו\"ל וחזרתי לארץ לפני 3 שנים. האנגלית שלי ברמת שפת אם. אשמח לעזור לכולם להשתפר.",
    categories: ["לימודי"],
    isApproved: true,
    helpCount: 9,
    approvalStatus: "approved",
    submittedAt: "2024-09-08T12:00:00",
  },
  {
    id: "h5",
    userId: "u11",
    skills: ["קשרים חברתיים", "חיבור אנשים", "אירוח"],
    availability: "כל יום בצהריים",
    bio: "אני אוהבת לפגוש אנשים חדשים ולעזור לכולם להרגיש שייכים. מאמינה שבית ספר טוב זה בית ספר שבו כולם מרגישים בבית.",
    categories: ["חברתי", "אירועים בית ספריים"],
    isApproved: true,
    helpCount: 4,
    approvalStatus: "approved",
    submittedAt: "2024-09-09T10:00:00",
  },
  {
    id: "h6",
    userId: "u8",
    skills: ["אנגלית", "הוראה", "הנחיה"],
    availability: "שעת הפסקה גדולה ואחרי שיעורים לפי תיאום",
    bio: "מורה לאנגלית עם 12 שנות ניסיון. מציע ייעוץ אישי לתלמידים המתכוננים לבגרות ולמבחנים בינלאומיים.",
    categories: ["לימודי"],
    isApproved: true,
    helpCount: 21,
    approvalStatus: "approved",
    submittedAt: "2024-09-03T08:00:00",
  },
  // ── Pending helper profiles (waiting for admin approval) ───────────────────
  {
    id: "h7",
    userId: "u4",
    skills: ["ציור", "אמנות", "עיצוב", "יצירה ידנית"],
    availability: "ימי א' ו-ה' בהפסקה הגדולה",
    bio: "אני אוהבת אמנות מגיל קטן. יש לי ניסיון בציור, פסל ועיצוב. אשמח לעזור לכל מי שצריך עזרה בפרויקטים יצירתיים.",
    categories: ["יצירתי"],
    isApproved: false,
    helpCount: 0,
    approvalStatus: "pending",
    submittedAt: "2025-04-10T09:15:00",
  },
  {
    id: "h8",
    userId: "u2",
    skills: ["ספרות", "עברית", "סיפור סיפורים"],
    availability: "ימי ב' בצהריים",
    bio: "מאוד אוהבת ספרות עברית וקריאה. רוצה לעזור לחברים שמתקשים בקריאה ובהבנת טקסטים.",
    categories: ["לימודי", "יצירתי"],
    isApproved: false,
    helpCount: 0,
    approvalStatus: "pending",
    submittedAt: "2025-04-10T11:00:00",
  },
];

export const MOCK_POINTS_EVENTS: PointsEvent[] = [
  {
    id: "pe1",
    userId: "u3",
    points: 30,
    reason: "השלמת עזרה בפרויקט היסטוריה",
    eventType: "complete",
    createdAt: "2025-01-08T17:00:00",
    relatedRequestId: "r7",
  },
  {
    id: "pe2",
    userId: "u3",
    points: 10,
    reason: "התנדבות לעזרה במחשבים",
    eventType: "volunteer",
    createdAt: "2025-01-06T10:00:00",
    relatedRequestId: "r2",
  },
  {
    id: "pe3",
    userId: "u1",
    points: 10,
    reason: "התנדבות לטקס יום הזיכרון",
    eventType: "volunteer",
    createdAt: "2025-01-10T09:00:00",
    relatedRequestId: "r4",
  },
  {
    id: "pe4",
    userId: "u1",
    points: 5,
    reason: "פרסום בקשה לגינה קהילתית",
    eventType: "publish_request",
    createdAt: "2025-01-07T09:00:00",
    relatedRequestId: "r9",
  },
  {
    id: "pe5",
    userId: "u11",
    points: 25,
    reason: "פרופיל עוזר אושר על ידי מנחם הרצוג",
    eventType: "profile_approved",
    createdAt: "2025-01-09T11:00:00",
  },
  {
    id: "pe6",
    userId: "u11",
    points: 10,
    reason: "התנדבות לחניכת תלמיד חדש",
    eventType: "volunteer",
    createdAt: "2025-01-10T09:00:00",
    relatedRequestId: "r5",
  },
  {
    id: "pe7",
    userId: "u3",
    points: 20,
    reason: "קבלת משוב חיובי מנעמה שפירא",
    eventType: "feedback_received",
    createdAt: "2025-01-09T08:00:00",
    relatedRequestId: "r7",
  },
  {
    id: "pe8",
    userId: "u12",
    points: 10,
    reason: "התנדבות לקבוצת לימוד אנגלית",
    eventType: "volunteer",
    createdAt: "2025-01-11T11:00:00",
    relatedRequestId: "r8",
  },
];
