import { HelpRequest } from "@/lib/types";

export const MOCK_REQUESTS: HelpRequest[] = [
  {
    id: "r1",
    title: "עזרה בהכנה לבגרות במתמטיקה 5 יחידות",
    category: "לימודי",
    description:
      "אני צריכה עזרה בהכנה לבגרות במתמטיקה 5 יחידות, בעיקר בנושא מחשבון גרפי ופונקציות. מחפשת מישהו שיכול לעזור שעתיים בשבוע לפחות עד מועד א'.",
    targetAudience: "תלמידים וצוות מורים",
    when: "ינואר–מרץ 2025, פעמיים בשבוע",
    status: "פתוח",
    urgency: "גבוהה",
    helpersNeeded: 1,
    assignedHelperIds: [],
    volunteerIds: ["u3"],
    createdById: "u2",
    createdAt: "2025-01-10T10:00:00",
    updatedAt: "2025-01-12T09:00:00",
    requiresStaffApproval: false,
    contactPerson: "מיה לוי",
    approvalStatus: "approved",
    updates: [
      {
        id: "upd1",
        text: "יש מתנדב ראשון! נא לאשר התאמה.",
        authorId: "u9",
        createdAt: "2025-01-12T09:00:00",
        isStaffNote: true,
      },
    ],
  },
  {
    id: "r2",
    title: "תיקון ומיחזור מחשבים ישנים של בית הספר",
    category: "טכני",
    description:
      "יש לנו 8 מחשבים ישנים שצריכים בדיקה, ניקוי וארגון מחדש. מחפשים תלמידים שמבינים בטכנולוגיה שיעזרו לנו להחיות אותם ולתרום אותם לכיתות.",
    targetAudience: "תלמידים עם רקע טכני",
    when: "ינואר 2025, כשבוע עבודה",
    status: "בטיפול",
    urgency: "בינונית",
    helpersNeeded: 3,
    assignedHelperIds: ["u3", "u5"],
    volunteerIds: ["u3", "u5", "u6"],
    createdById: "u9",
    createdAt: "2025-01-05T08:00:00",
    updatedAt: "2025-01-11T14:00:00",
    requiresStaffApproval: true,
    contactPerson: "דבורה כץ",
    approvalStatus: "approved",
    updates: [
      {
        id: "upd2",
        text: "שני תלמידים הצטרפו לפרויקט. נתחיל ביום שלישי בצהריים.",
        authorId: "u9",
        createdAt: "2025-01-11T14:00:00",
        isStaffNote: false,
      },
    ],
  },
  {
    id: "r3",
    title: "חברה לפרויקט אמנות – עיצוב לוגו לעיתון בית הספר",
    category: "יצירתי",
    description:
      "מחפשת שותפ/ה ליצירה – צריכים לעצב לוגו חדש ומרגש לעיתון הבית ספרי 'קולות'. יש ניסיון בעיצוב? תואמ/ת מושלמ/ת!",
    targetAudience: "תלמידים עם יכולות עיצוב",
    when: "פברואר 2025",
    status: "פתוח",
    urgency: "נמוכה",
    helpersNeeded: 2,
    assignedHelperIds: [],
    volunteerIds: [],
    createdById: "u4",
    createdAt: "2025-01-08T15:30:00",
    updatedAt: "2025-01-08T15:30:00",
    requiresStaffApproval: false,
    contactPerson: "נעמה שפירא",
    approvalStatus: "approved",
    updates: [],
  },
  {
    id: "r4",
    title: "עזרה בארגון טקס יום הזיכרון",
    category: "אירועים בית ספריים",
    description:
      "בית הספר מארגן טקס יום הזיכרון לחללי צה״ל. אנחנו מחפשים תלמידים שרוצים לעזור בהפקה – קריינות, סידור כיסאות, קריאת שמות, ליווי משפחות.",
    targetAudience: "כלל התלמידים",
    when: "אפריל 2025",
    status: "פתוח",
    urgency: "בינונית",
    helpersNeeded: 8,
    assignedHelperIds: ["u1", "u12"],
    volunteerIds: ["u1", "u2", "u12", "u11"],
    createdById: "u7",
    createdAt: "2025-01-09T11:00:00",
    updatedAt: "2025-01-13T10:00:00",
    requiresStaffApproval: true,
    contactPerson: "גב' רחל גולן",
    approvalStatus: "approved",
    updates: [
      {
        id: "upd3",
        text: "ארבעה תלמידים הצטרפו. עדיין צריכים עוד ארבעה!",
        authorId: "u7",
        createdAt: "2025-01-13T10:00:00",
        isStaffNote: false,
      },
    ],
  },
  {
    id: "r5",
    title: "חניכה לתלמיד חדש שהצטרף לכיתה ח'",
    category: "חברתי",
    description:
      "הצטרף אלינו תלמיד חדש לכיתה ח'2. הוא עלה לאחרונה ועברית שוטפת עוד בהתפתחות. מחפשים תלמיד/ה חמימ/ת שיסייע לו להשתלב חברתית ולימודית.",
    targetAudience: "תלמידים כיתות ח'–ט'",
    when: "מיידי, לאורך המחצית",
    status: "בטיפול",
    urgency: "דחוף",
    helpersNeeded: 1,
    assignedHelperIds: ["u11"],
    volunteerIds: ["u11"],
    createdById: "u7",
    createdAt: "2025-01-06T08:30:00",
    updatedAt: "2025-01-10T09:00:00",
    requiresStaffApproval: true,
    contactPerson: "גב' רחל גולן",
    approvalStatus: "approved",
    updates: [
      {
        id: "upd4",
        text: "תמר ניסים קיבלה את המשימה. סיכמנו שאחת לשבוע הן נפגשות לארוחת צהריים.",
        authorId: "u7",
        createdAt: "2025-01-10T09:00:00",
        isStaffNote: false,
      },
    ],
  },
  {
    id: "r6",
    title: "ריכוז ועדכון לוח הזמנים של הספרייה",
    category: "ארגוני",
    description:
      "הספרייה זקוקה לעזרה בעדכון מלאי הספרים, סידור המדפים מחדש ויצירת לוח השאלה דיגיטלי. עבודה מסודרת ומשתלמת.",
    targetAudience: "תלמידים וצוות",
    when: "ינואר–פברואר 2025",
    status: "פתוח",
    urgency: "נמוכה",
    helpersNeeded: 2,
    assignedHelperIds: [],
    volunteerIds: ["u6"],
    createdById: "u9",
    createdAt: "2025-01-03T12:00:00",
    updatedAt: "2025-01-07T11:00:00",
    requiresStaffApproval: false,
    contactPerson: "דבורה כץ",
    approvalStatus: "approved",
    updates: [],
  },
  {
    id: "r7",
    title: "הכנת מצגת לפרויקט בהיסטוריה",
    category: "לימודי",
    description:
      "אני לא כל כך מצליחה לארגן את המחקר שלי לפרויקט בהיסטוריה (נושא: המנדט הבריטי). מחפשת מישהו שיעזור לי לסדר את החומר ולהכין מצגת ב-PowerPoint.",
    targetAudience: "תלמידים",
    when: "ינואר 2025, עד סוף החודש",
    status: "הושלם",
    urgency: "גבוהה",
    helpersNeeded: 1,
    assignedHelperIds: ["u3"],
    volunteerIds: ["u3"],
    createdById: "u4",
    createdAt: "2024-12-20T14:00:00",
    updatedAt: "2025-01-08T17:00:00",
    requiresStaffApproval: false,
    contactPerson: "נעמה שפירא",
    approvalStatus: "approved",
    updates: [
      {
        id: "upd5",
        text: "הפרויקט הוגש! תודה עצומה ליונתן שעזר לי להבין את הנושא ולארגן את החומר.",
        authorId: "u4",
        createdAt: "2025-01-08T17:00:00",
        isStaffNote: false,
      },
    ],
  },
  {
    id: "r8",
    title: "שיעורי אנגלית לבגרות – קבוצת לימוד",
    category: "לימודי",
    description:
      "מחפשים תלמידים ברמת אנגלית גבוהה שמוכנים לנהל קבוצת לימוד לקראת בגרות. מר שלום מוכן לתמוך ולתאם. מחפשים 2–3 מתנדבים.",
    targetAudience: "תלמידי י' ו-י\"א",
    when: "פברואר–מרץ 2025, אחת לשבוע",
    status: "פתוח",
    urgency: "בינונית",
    helpersNeeded: 3,
    assignedHelperIds: [],
    volunteerIds: ["u12"],
    createdById: "u8",
    createdAt: "2025-01-11T10:30:00",
    updatedAt: "2025-01-11T10:30:00",
    requiresStaffApproval: true,
    contactPerson: "מר אמיר שלום",
    approvalStatus: "approved",
    updates: [],
  },
  {
    id: "r9",
    title: "עזרה בהקמת גינה קהילתית בחצר",
    category: "קהילתי",
    description:
      "בית הספר מתכנן להקים גינה קהילתית בחצר הפנימית. מחפשים תלמידים שאוהבים טבע, חקלאות, ורוצים להשתתף בתכנון, שתילה ותחזוקה שוטפת.",
    targetAudience: "כלל התלמידים והורים",
    when: "פברואר–מאי 2025",
    status: "פתוח",
    urgency: "נמוכה",
    helpersNeeded: 5,
    assignedHelperIds: [],
    volunteerIds: ["u1", "u2", "u4"],
    createdById: "u9",
    createdAt: "2025-01-07T09:00:00",
    updatedAt: "2025-01-14T08:00:00",
    requiresStaffApproval: true,
    contactPerson: "דבורה כץ",
    approvalStatus: "approved",
    updates: [],
  },
  // ── Pending requests (waiting for admin approval) ──────────────────────────
  {
    id: "r10",
    title: "קבוצת תמיכה לתלמידים חרדים לבחינות",
    category: "חברתי",
    description:
      "רוצה לייסד קבוצת תמיכה רגשית לתלמידים שסובלים מחרדת בחינות. מחפשת חברים שעברו דבר דומה ומוכנים לשתף.",
    targetAudience: "תלמידי י'–י\"ב",
    when: "לפני כל מועד בחינות",
    status: "פתוח",
    urgency: "גבוהה",
    helpersNeeded: 4,
    assignedHelperIds: [],
    volunteerIds: [],
    createdById: "u6",
    createdAt: "2025-04-10T08:30:00",
    updatedAt: "2025-04-10T08:30:00",
    requiresStaffApproval: false,
    contactPerson: "שיר אביב",
    approvalStatus: "pending",
    updates: [],
  },
  {
    id: "r11",
    title: "עזרה בהפקת סרטון לסיום שנה",
    category: "יצירתי",
    description:
      "מחפשים עורכי וידאו ומצלמים שיעזרו להפיק סרטון תודה מיוחד לכבוד סיום שנת הלימודים. ניסיון בעריכה יתרון.",
    targetAudience: "כלל התלמידים",
    when: "מאי–יוני 2025",
    status: "פתוח",
    urgency: "בינונית",
    helpersNeeded: 3,
    assignedHelperIds: [],
    volunteerIds: [],
    createdById: "u1",
    createdAt: "2025-04-10T10:00:00",
    updatedAt: "2025-04-10T10:00:00",
    requiresStaffApproval: false,
    contactPerson: "אור כהן",
    approvalStatus: "pending",
    updates: [],
  },
];
