import { User } from "@/lib/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "אור כהן",
    role: "student",
    class: "י'2",
    avatarInitials: "אכ",
    avatarColor: "bg-blue-500",
    points: 420,
    rank: "מוביל/ה",
    joinedAt: "2024-09-01",
    isActive: true,
  },
  {
    id: "u2",
    name: "מיה לוי",
    role: "student",
    class: "ט'1",
    avatarInitials: "מל",
    avatarColor: "bg-pink-500",
    points: 185,
    rank: "תורם/ת",
    joinedAt: "2024-09-01",
    isActive: true,
  },
  {
    id: "u3",
    name: "יונתן בן-דוד",
    role: "student",
    class: "י\"א3",
    avatarInitials: "יב",
    avatarColor: "bg-green-500",
    points: 730,
    rank: "מאסטר/ית",
    joinedAt: "2023-09-01",
    isActive: true,
  },
  {
    id: "u4",
    name: "נעמה שפירא",
    role: "student",
    class: "ח'2",
    avatarInitials: "נש",
    avatarColor: "bg-purple-500",
    points: 60,
    rank: "פעיל/ה",
    joinedAt: "2024-09-01",
    isActive: true,
  },
  {
    id: "u5",
    name: "דניאל מזרחי",
    role: "student",
    class: "י'4",
    avatarInitials: "דמ",
    avatarColor: "bg-amber-500",
    points: 310,
    rank: "תורם/ת",
    joinedAt: "2024-09-01",
    isActive: true,
  },
  {
    id: "u6",
    name: "שיר אביב",
    role: "student",
    class: "י\"א1",
    avatarInitials: "שא",
    avatarColor: "bg-teal-500",
    points: 25,
    rank: "מתחיל/ה",
    joinedAt: "2025-01-15",
    isActive: true,
  },
  {
    id: "u7",
    name: "גב' רחל גולן",
    role: "teacher",
    position: "מורה למתמטיקה",
    avatarInitials: "רג",
    avatarColor: "bg-indigo-500",
    points: 540,
    rank: "מוביל/ה",
    joinedAt: "2023-09-01",
    isActive: true,
  },
  {
    id: "u8",
    name: "מר אמיר שלום",
    role: "teacher",
    position: "מורה לאנגלית",
    avatarInitials: "אש",
    avatarColor: "bg-cyan-500",
    points: 870,
    rank: "מאסטר/ית",
    joinedAt: "2022-09-01",
    isActive: true,
  },
  {
    id: "u9",
    name: "דבורה כץ",
    role: "staff",
    position: "רכזת חברתית",
    avatarInitials: "דכ",
    avatarColor: "bg-rose-500",
    points: 410,
    rank: "מוביל/ה",
    joinedAt: "2023-09-01",
    isActive: true,
  },
  {
    id: "u10",
    name: "מנחם הרצוג",
    role: "admin",
    position: "מנהל מערכת",
    avatarInitials: "מה",
    avatarColor: "bg-slate-600",
    points: 1200,
    rank: "מאסטר/ית",
    joinedAt: "2022-09-01",
    isActive: true,
  },
  {
    id: "u11",
    name: "תמר ניסים",
    role: "student",
    class: "ט'3",
    avatarInitials: "תנ",
    avatarColor: "bg-orange-500",
    points: 95,
    rank: "פעיל/ה",
    joinedAt: "2024-09-01",
    isActive: true,
  },
  {
    id: "u12",
    name: "ליאור פרידמן",
    role: "student",
    class: "י\"ב2",
    avatarInitials: "לפ",
    avatarColor: "bg-lime-500",
    points: 510,
    rank: "מוביל/ה",
    joinedAt: "2022-09-01",
    isActive: true,
  },
];

// The "current user" for mock purposes — can be changed in the AuthContext
export const CURRENT_USER_ID = "u1";
